### ISSUE TITLE
kf5-kwallet Error: Failure while executing: patch -g 0 -f -p1

### ISSUE THREAD

**Issue by vaboro** [KDE-mac/homebrew-kde#194]
$ brew upgrade kf5-kwallet
==> Upgrading 1 outdated package, with result:
kde-mac/kde/kf5-kwallet 5.41.0_1
==> Upgrading kde-mac/kde/kf5-kwallet
==> Downloading https://download.kde.org/stable/frameworks/5.41/kwallet-5.41.0.tar.xz
==> Patching
patching file CMakeLists.txt
Hunk #1 FAILED at 21.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
patching file src/runtime/kwallet-query/src/CMakeLists.txt
patching file src/runtime/kwalletd/CMakeLists.txt
Error: Failure while executing: patch -g 0 -f -p1

**Comment by ftonello** [comment]
I can verify it here.

**Comment by ynakao** [comment]
I have the same issue. Is this because [a new line](https://github.com/KDE/kwallet/commit/e10582db32e468444d6bb41fd3dad92950b8f2de#diff-af3b638bc2a3e6c650974192a53c7291R24) (`include(ECMQtDeclareLoggingCategory)`) was added in `CMakeLists.txt` in the version 5.41.0, and conflicts with the current patch?

I tried to make a new patch adding `include(ECMMarkNonGuiExecutable)` after `include(ECMQtDeclareLoggingCategory)` in `kf5-kwallet.rb`, and the compile succeeded.

```
...
  include(ECMAddQch)
  include(ECMSetupVersion)
  include(ECMQtDeclareLoggingCategory)
 +include(ECMMarkNonGuiExecutable)
...
```

But I'm not familiar with the kwallet build process, so don't know this approach is the proper workaround. Any suggestions?

**Comment by vaboro** [comment]
Unfortunately, I'm not familiar with kwallet build process either, but your approach worked for me.

**Comment by bmihaila** [comment]
@ynakao your patch works for me too. Can you open a pull req? Then we could close this issue. Or did you already do so?

**Comment by ynakao** [comment]
I just submitted the PR (#197). Please wait for maintainers review.

**Comment by bmihaila** [comment]
@ynakao so I guess this is now fixed with the MR and the issue can be closed? If so can you close it?

**Comment by ynakao** [comment]
@bmihaila Sorry, I don't have permission to close this issue. Maybe @vaboro(OP) or @yurikoles(Collaborator) can do that.

**Comment by vaboro** [comment]
Closed. Thanks for reminding.
